<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Wurs.Test.Utilities.Moq</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Wurs.Test.Utilities.NSubstitute</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Wurs.Test.Utilities.ManualTests\**\*.cs" />
		<EmbeddedResource Remove="Wurs.Test.Utilities.ManualTests\**\*" />
		<None Remove="Wurs.Test.Utilities.ManualTests\**\*" />
	</ItemGroup>

</Project>